[web]
web-server ansible_host=i-0b266c506a0624028 private_ip=10.0.0.5

[ansible_controller]
ansible-controller ansible_host=i-03a633e1835255523 private_ip=10.0.0.135

[monitoring]
monitoring-server ansible_host=i-0376c2fafcfd64987 private_ip=10.0.0.136

[prometheus_exporters]
web-server
ansible-controller
monitoring-server

[all:vars]
ansible_user=ubuntu
ansible_connection=amazon.aws.aws_ssm
ansible_python_interpreter=/usr/bin/python3
repo_url=260080159789.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/final-project-fakhrul