[web_server]
web-server ansible_host=i-05f21b06a12f74e9a instance_id=i-05f21b06a12f74e9a private_ip=10.0.0.5 public_ip=54.179.206.243

[ansible_controller]
ansible-controller ansible_host=i-01d93c399451011e2 instance_id=i-01d93c399451011e2 private_ip=10.0.0.135 public_ip=

[monitoring_server]
monitoring-server ansible_host=i-09b1827dfd97635e6 instance_id=i-09b1827dfd97635e6 private_ip=10.0.0.136 public_ip=

[prometheus_exporters]
web-server ansible_host=i-05f21b06a12f74e9a
ansible-controller ansible_host=i-01d93c399451011e2
monitoring-server ansible_host=i-09b1827dfd97635e6

[all:vars]
ansible_user=ubuntu
ansible_connection=amazon.aws.aws_ssm
ansible_python_interpreter=/usr/bin/python3
repo_url=260080159789.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/final-project-fakhrul