# inventory.tftpl

[nodes]
web-server ansible_host=10.0.0.5
ansible-controller ansible_host=10.0.0.135
monitoring-server ansible_host=10.0.0.136

[web_server]
web-server ansible_host=10.0.0.5

[ansible_controller]
ansible-controller ansible_host=10.0.0.135

[monitoring_server]
monitoring-server ansible_host=10.0.0.136

[prometheus_exporters]
web-server ansible_host=10.0.0.5
ansible-controller ansible_host=10.0.0.135
monitoring-server ansible_host=10.0.0.136

[ecr_repo] repo_url=260080159789.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/final-project-fakhrul

[all:vars]
ansible_user=ubuntu
ansible_connection=amazon.aws.aws_ssm
ansible_python_interpreter=/usr/bin/python3