---
- name: Build and Push Docker Image to ECR
  hosts: localhost
  connection: local
  #become: true
  vars:
    repo_url: "{{ repo_url }}"
  tasks:
    - name: Clone lab-final-project repo
      git:
        repo: "https://github.com/Infratify/lab-final-project.git"
        dest: ./lab-final-project
        version: HEAD
        force: yes

    - name: Build my-devops-project image
      docker_image:
        name: my-devops-project
        tag: latest
        build:
          path: ./lab-final-project
        source: build

    - name: Tag image for ECR
      command: >
        docker tag my-devops-project:latest {{ repo_url }}:latest

    - name: Push image to ECR
      command: >
        docker push {{ repo_url }}:latest
