########################################
# Generate Ansible Playbook:
# Build & Push Docker Image to ECR
########################################
resource "local_file" "ecr_build_push_playbook" {
  filename = "${path.module}/../ansible/build_and_push_ecr.yml"

  content = <<-EOF
---
# This playbook is autogenerated by Terraform
# Do NOT edit manually

- name: Build and Push Docker Image to ECR
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Clone lab-final-project repo
      git:
        repo: "https://github.com/Infratify/lab-final-project.git"
        dest: ./lab-final-project
        version: HEAD
        force: yes

    - name: Build Docker image
      community.docker.docker_image:
        name: my-devops-project
        tag: latest
        build:
          path: ./lab-final-project
        source: build

    - name: Tag image for ECR
      command: >
        docker tag my-devops-project:latest {{ repo_url }}:latest

    - name: Push image to ECR
      command: >
        docker push {{ repo_url }}:latest
EOF
}
